services:

  template-dev:
    build:
      context: .
      target: dev
    image: template:dev
    ports:
      - '8001:8001'
    environment:
      - DATABASE_URL=postgresql://admin:admin@template-db-dev:5432/template_name_db
    networks:
      - template-network-dev
    depends_on:
      - template-db-dev

  template-db-dev:
    image: postgres:18.1-alpine3.23
    container_name: template-db-dev
    volumes:
      - template-volume-data-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=template_name_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - template-network-dev
    ports:
      - "5432:5432"

networks:
  template-network-dev:
    name: template-network-dev
    driver: bridge

volumes:
  template-volume-data-dev:
    name: template-volume-data-dev
    driver: local