services:

  identity-db-simple:
    image: postgres:18.1-alpine3.23
    container_name: identity-db-simple
    volumes:
      - indentity-data-simple:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "8432:5432"

volumes:
  indentity-data-simple:
    driver: local