services:
  identity-dev:
    build:
      context: ./identity-service
      target: dev
    image: identity:dev
    volumes:
      - ./identity-service/app:/app
    ports:
      - '8001:8001'
    environment:
      - DATABASE_URL=postgresql://admin:admin@identity-db-dev:5432/users
    networks:
      - assicura-app-dev
    depends_on:
      - identity-db-dev
  driver-license-dev:
    build:
      context: ./driver-license-service
      target: dev
    image: driver-license:dev
    volumes:
      - ./driver-license-service/app:/app
    ports:
      - '8002:8001'
    environment:
      - DATABASE_URL=postgresql://admin:admin@driver-license-db-dev:5432/driver-license
    networks:
      - assicura-app-dev
    depends_on:
      - driver-license-db-dev


  identity-db-dev:
    image: postgres:18.1-alpine3.23
    container_name: identity-db-dev
    volumes:
      - identity-data-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - assicura-app-dev
    ports:
      - "5432:5432"

  driver-license-db-dev:
    image: postgres:18.1-alpine3.23
    container_name: driver-license-db-dev
    volumes:
      - driver-license-data-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=driver-license
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - assicura-app-dev
    ports:
      - "5433:5432"

networks:
  assicura-app-dev:
    name: assicura-app-dev
    driver: bridge

volumes:
  driver-license-data-dev:
    driver: local

  identity-data-dev:
    driver: local
